---
title: Savory Readings
baseline: ''
description: a lenormand blog
baseurl: "/"
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: America/Los_Angeles
pagination:
  max: "5"
  path: page
output:
  formats:
    netlify_redirects:
      mediatype: text/plain
      extension: ''
virtualpages:
  admin:
    layout: admin/index
    output: html
    title: Content Manager (Netlify CMS)
  _redirects:
    output: netlify_redirects
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
